# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a44a0209ed4518b36730c888598d114f060825d23a2debe3650cc09f4c533caabc0a8175bba9d0f496f7faea90bddb273aea6fddbf3654bcd1b9d61f092253cf

test:
  secret_key_base: 40d5c2d4ee89f9997a072ed65b71b9b9e27707097f8f4618beac43fc8f7b28c8338f6c61dc974d01c0fab2bd1ff0c5a036397635d912aff41be78510f0d8c091

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
